name: traveljournal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  chewie: ^1.5.0
  flutter_compass: ^0.8.1  # For compass functionality
  shimmer: ^3.0.0 
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  video_player: ^2.9.3
  audioplayers: ^5.0.0
  just_audio: ^0.9.46
  shared_preferences: ^2.5.2
  path_provider: ^2.0.11
  path: ^1.8.2
  # For generating word clouds
  fl_chart: ^0.63.0   # For displaying sentiment analysis graphs
 
  image: ^4.0.17
  audio_service: ^0.18.9
  sentiment_dart: ^0.0.5  # For sentiment analysis
  
  uri_parser: ^1.0.0
  youtube_explode_dart: ^2.3.9
  http: ^1.0.0


  cached_network_image: ^3.2.3

  appwrite: ^14.0.0
  flutter_appauth: ^8.0.3
  youtube_player_flutter: ^8.1.2
  device_info_plus: ^10.1.2
  flutter_drawing_board: ^0.9.8
  latlong2: ^0.9.1
  intl: ^0.20.2
  flutter_typeahead: ^4.1.0  
  flutter_map: ^8.1.1
  confetti: ^0.8.0
  vector_math: ^2.1.4
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/travel_background.jpg
    - assets/loginpage.jpg
    - assets/google.png
    - assets/homepage.jpg
    - fonts/DeliciousHandrawn-Regular.ttf
  fonts:
    - family: DeliciousHandrawn
      fonts:
        - asset: fonts/DeliciousHandrawn-Regular.ttf
    - family: Schoolbell
      fonts:
        - asset: fonts/Schoolbell-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-LightItalic.ttf
    - family: Inter
      fonts:
        - asset: fonts/inter-light.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf